import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { push } = useRouter();
  useEffect(() => {
    push("/dashboard");
  }, []); // eslint-disable-line

  return (
    <div>
      <Head>
        <title>MSys Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "white",
        }}
      >
        Dashboard
      </div>
    </div>
  );
};

export default Home;
